services:
  frontend:
    image: node:22-alpine
    volumes:
      - ./frontend:/app

    ports:
      - 80:5000
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
      - ./backend/.env:/app/.env
      - ./backend/env:/app/env
      - ./backend/requirements.txt:/app/requirements.txt
    ports:
      - 3000:5000
    
    env_file:
      - ./backend/.env
    depends_on:
      - database

  database:
    image: postgres:latest

    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
